# Generated by Django 3.2.8 on 2021-10-15 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedditPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=8, unique=True)),
                ('ticker_type', models.CharField(max_length=16)),
                ('on_robinhood', models.BooleanField(default=False)),
            ],
        ),
    ]
